# Generated by Django 3.2.3 on 2021-05-17 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('course_rating_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('summed_votes', models.PositiveIntegerField(default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='courses.course')),
            ],
        ),
    ]
