# Generated by Django 3.2.3 on 2021-05-17 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('moed', models.PositiveSmallIntegerField()),
                ('students_count', models.PositiveSmallIntegerField()),
                ('failures_count', models.PositiveSmallIntegerField()),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.coursegroup')),
            ],
            options={
                'ordering': ('course_group', 'moed'),
                'unique_together': {('course_group', 'moed')},
            },
        ),
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('exam_statistics_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='grades.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGradeRange',
            fields=[
                ('exam_grade_range_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lowest_grade', models.PositiveSmallIntegerField()),
                ('highest_grade', models.PositiveSmallIntegerField()),
                ('students_in_range', models.PositiveSmallIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.exam')),
            ],
            options={
                'ordering': ('lowest_grade',),
                'unique_together': {('exam', 'lowest_grade')},
            },
        ),
    ]
