# Generated by Django 3.2.3 on 2021-11-10 21:28

import common.defines
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import teachers.defines
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hebrew_teacher_name', models.CharField(db_index=True, max_length=255)),
                ('english_teacher_name', models.CharField(db_index=True, max_length=255)),
                ('latest_honorific', enumchoicefield.fields.EnumChoiceField(enum_class=teachers.defines.Honorific, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherHonorific',
            fields=[
                ('teacher_honorific_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('honorific', enumchoicefield.fields.EnumChoiceField(enum_class=teachers.defines.Honorific, max_length=4)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2040)])),
                ('semester', enumchoicefield.fields.EnumChoiceField(enum_class=common.defines.Semester, max_length=8)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorifics', to='teachers.teacher')),
            ],
        ),
    ]
