# Generated by Django 3.2.3 on 2021-07-27 17:24

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_index=True, max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Course code format must be xxxx-xxxx', regex=re.compile('^\\d{4}-\\d{4}$'))]),
        ),
    ]
